### ISSUE TITLE
Python compiling error

### ISSUE THREAD

**Issue by jchao2001** [neonexchange/neo-ico-template#3]
>>> Compiler.load_and_save('ico_template.py')
LOADING AND SAVING! ico_template.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35-32\lib\site-packages\neo_boa-0.2.0-py3.5.egg\boa\compiler.py", line 106, in load_and_save
    compiler = Compiler.load(path)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35-32\lib\site-packages\neo_boa-0.2.0-py3.5.egg\boa\compiler.py", line 139, in load
    module = Module(path)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35-32\lib\site-packages\neo_boa-0.2.0-py3.5.egg\boa\code\module.py", line 237, in __init__
    self.build()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35-32\lib\site-packages\neo_boa-0.2.0-py3.5.egg\boa\code\module.py", line 261, in build
    imp = Import(lineset.items, self.path)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35-32\lib\site-packages\neo_boa-0.2.0-py3.5.egg\boa\code\items.py", line 228, in __init__
    self.build()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35-32\lib\site-packages\neo_boa-0.2.0-py3.5.egg\boa\code\items.py", line 237, in build
    module = importlib.import_module(self.module_path, self.module_path)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 931, in _sanity_check
**SystemError: Parent module 'boa.blockchain.vm.Neo.Runtime' not loaded, cannot perform relative import**

**Comment by adarshaJha** [comment]
**getting same error ******
